services: 
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=aave-store
    volumes:
      - postgres:/var/lib/postgresql/data
  
  defi-bot:
    container_name: defi-bot
    build: .
    depends_on:
      - database
    volumes:
      - ./config/default.json:/app/dist/config/default.json

volumes:
  postgres:
    driver: local
